# Generated by Django 5.1.3 on 2024-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_image', models.ImageField(upload_to='man_image/')),
                ('woman_image', models.ImageField(upload_to='woman_image/')),
            ],
        ),
    ]
